import StoreProvider from './StoreProvider';
import axios from 'axios';
import './globals.css';
import { getAuthToken } from '@/lib/autheticate';

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const authData = await checkAuthStatus();
  return (
    <html>
      <head />
      <body>
        <StoreProvider authData={authData}>
          {children}
        </StoreProvider>
      </body>
    </html>
  )
}

async function checkAuthStatus() {
  try{
    const token = getAuthToken(); 

    const response = await axios.get('http://localhost:3000/api/auth/me', {
      headers: { 'Authorization': `Bearer ${token}` }
    });

    return response?.data?.data || null;
  } catch({response}) {
    console.log('error response: user Browsing', response?.data);
  }
}
