
const getMeasurementUnits = () => {
    return [
      { "label": "Kilogram", "value": "kg" },
      { "label": "Gram", "value": "g" },
      { "label": "Pound", "value": "lb" },
      { "label": "Ounce", "value": "oz" },
      { "label": "Ton", "value": "ton" },
      { "label": "Metric Ton", "value": "t" },
      { "label": "Liter", "value": "L" },
      { "label": "Milliliter", "value": "mL" },
      { "label": "Gallon (US)", "value": "gal" },
      { "label": "Fluid Ounce (US)", "value": "fl oz" },
      { "label": "Pint (US)", "value": "pt" },
      { "label": "Quart (US)", "value": "qt" },
      { "label": "Foot", "value": "ft" },
      { "label": "Inch", "value": "in" },
      { "label": "Meter", "value": "m" },
      { "label": "Centimeter", "value": "cm" },
      { "label": "Yard", "value": "yd" },
      { "label": "Mile", "value": "mi" },
      { "label": "Square Meter", "value": "sq m" },
      { "label": "Square Foot", "value": "sq ft" },
      { "label": "Square Inch", "value": "sq in" },
      { "label": "Acre", "value": "ac" },
      { "label": "Hectare", "value": "ha" },
      { "label": "Piece", "value": "pc" },
      { "label": "Dozen", "value": "dz" },
      { "label": "Pair", "value": "pr" },
      { "label": "Set", "value": "set" },
      { "label": "Bundle", "value": "bdl" },
      { "label": "Roll", "value": "roll" },
      { "label": "Box", "value": "box" },
      { "label": "Carton", "value": "ctn" },
      { "label": "Crate", "value": "crt" },
      { "label": "Barrel", "value": "bbl" },
      { "label": "Bag", "value": "bag" },
      { "label": "Sack", "value": "sack" },
      { "label": "Container", "value": "cntr" },
      { "label": "Pallet", "value": "plt" },
      { "label": "Truckload", "value": "tl" }, 
      { "label": "Carload", "value": "cl" },
      { "label": "Cubic Meter", "value": "cu m" },
      { "label": "Cubic Foot", "value": "cu ft" },
      { "label": "Cubic Yard", "value": "cu yd" },  
      { "label": "Celsius", "value": "°C" },
      { "label": "Fahrenheit", "value": "°F" },
      { "label": "Kelvin", "value": "K" },
      { "label": "Watt", "value": "W" },
      { "label": "Joule", "value": "J" },
      { "label": "Volt", "value": "V" },
      { "label": "Ampere", "value": "A" }
    ]       
}

export default getMeasurementUnits;